### ISSUE TITLE
login issues

### ISSUE THREAD

**Issue by joehand** [joehand/dat-next#98] opened 2017-01-24 23:04 UTC
```
❯ dat-next --server=http://localhost:8888/api/v1 login
Email: joe@hand.email
Password: **

Cannot read property 'email' of undefined
```

Not sure if on cli or datfolder side.

**Comment by okdistribute** [comment] 2017-01-24 23:26
do you need to have `/api/v1`

**Comment by joehand** [comment] 2017-01-24 23:42
Reproduce:

* run `npm run auth-server` in dat-next

In a dat folder:

1. `dat-next create --import`
2. `dat-next --server=http://localhost:8888/api/v1 register` with username `person`
3. `dat-next --server=http://localhost:8888/api/v1 login`
4. `dat-next --server=http://localhost:8888/api/v1 publish --name dataset`
5. Visit http://localhost:8888/person/dataset

After visiting o/ I crash the server and get error (make sure the dat isn't being shared):

```
Assertion failed: (!uv__io_active(&handle->io_watcher, POLLIN | POLLOUT)), function uv__udp_finish_close, file ../deps/uv/src/unix/udp.c, line 64.
```

6. Restart server
7. (back in dat folder) `dat-next --server=http://localhost:8888/api/v1 login`

**Comment by okdistribute** [comment] 2017-01-25 01:09
so did this get fixed? :P

**Comment by okdistribute** [comment] 2017-01-25 01:09
with 'I turned json true on for the clone which means i didnt have to parse the json' ?

**Comment by joehand** [comment] 2017-01-25 01:16
No this was separate, sorry.

**Comment by okdistribute** [comment] 2017-01-25 01:24
I don't see the bug if I run the server on my machine separate from `npm run auth-server` and I wasn't able to reproduce the bug with `npm run auth-server`

**Comment by joehand** [comment] 2017-01-25 01:26
Bug on My Machine™

**Comment by okdistribute** [comment] 2017-01-25 01:27
I spoke too quickly I was able to reproduce it with `npm run auth-server` but slightly differently on my machine.. still never reproduced on the actual deployment. I think its a bug in the auth-server code

**Comment by okdistribute** [comment] 2017-01-25 01:41
```
$ dat register --server=http://localhost:8888/api/v1 
Email: people
Username: hi
Password: **

A user already exists with that username.

$ dat login --server=http://localhost:8888/api/v1
Email: person
Password: **

Logged in successfully.

$ dat login --server=http://localhost:8888/api/v1
Email: people
Password: **

Trace: { statusCode: 400,
  message: 'Cannot read property \'email\' of undefined' }
    at /Users/karissa/node_modules/dat-next/lib/commands/auth/login.js:40:24
    at /Users/karissa/node_modules/dat-next/node_modules/township-client/index.js:69:21
    at Request._callback (/Users/karissa/node_modules/dat-next/node_modules/township-client/index.js:162:39)
    at Request.self.callback (/Users/karissa/node_modules/dat-next/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/karissa/node_modules/dat-next/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/karissa/node_modules/dat-next/node_modules/request/request.js:1001:12)
Cannot read property 'email' of undefined
```

**Comment by okdistribute** [comment] 2017-01-25 01:45
OK I committed the following patch which gives better error messages from the server

https://github.com/datproject/datfolder/commit/a1cba487d0abf9a678957fcfab1973fbe68e2717

**Comment by okdistribute** [comment] 2017-01-25 01:49
I think its just because when the auth server crashes it deletes the user database, and before the above patch if you tried to login with a user that didn't exist it would give you the email error

**Closed as completed** 2017-01-25 01:54 UTC
Labels: bug
